#include<iostream>	
#include<string.h>
using namespace std;

class NoPersonException
{
private:
	int persons;
public:
	NoPersonException();
	NoPersonException(int p) { persons = p; }
	int get_persons() { return persons; }
};

int main1()
{
	int pizza_slices = 0;
	int persons = 0;
	int slices_per_person = 0;
	try
	{
		cout << "피자 조각수를 입력: ";
		cin >> pizza_slices;
		cout << "사람수를 입력: ";
		cin >> persons;

		if (persons <= 0) throw NoPersonException(persons);
		slices_per_person = pizza_slices / persons;
		cout << "한 사람당 피자는 " << slices_per_person << "입니다." << endl;
	}
	catch (NoPersonException e)
	{
		cout << "오류: 사람 수가 " << e.get_persons() << "입니다" << endl;
	}
	
	return 0;
}
